// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pmt_cpp
NumericVector pmt_cpp(NumericVector rate, NumericVector nper, NumericVector pv);
RcppExport SEXP _optiRum_pmt_cpp(SEXP rateSEXP, SEXP nperSEXP, SEXP pvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nper(nperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pv(pvSEXP);
    rcpp_result_gen = Rcpp::wrap(pmt_cpp(rate, nper, pv));
    return rcpp_result_gen;
END_RCPP
}
// pv_cpp
NumericVector pv_cpp(NumericVector rate, NumericVector nper, NumericVector pmt);
RcppExport SEXP _optiRum_pv_cpp(SEXP rateSEXP, SEXP nperSEXP, SEXP pmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nper(nperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pmt(pmtSEXP);
    rcpp_result_gen = Rcpp::wrap(pv_cpp(rate, nper, pmt));
    return rcpp_result_gen;
END_RCPP
}
// ratecpp
NumericVector ratecpp(const NumericVector nper, const NumericVector pmt, const NumericVector pv);
RcppExport SEXP _optiRum_ratecpp(SEXP nperSEXP, SEXP pmtSEXP, SEXP pvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type nper(nperSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type pmt(pmtSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type pv(pvSEXP);
    rcpp_result_gen = Rcpp::wrap(ratecpp(nper, pmt, pv));
    return rcpp_result_gen;
END_RCPP
}
// times_two
NumericVector times_two(NumericVector x);
RcppExport SEXP _optiRum_times_two(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(times_two(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_optiRum_pmt_cpp", (DL_FUNC) &_optiRum_pmt_cpp, 3},
    {"_optiRum_pv_cpp", (DL_FUNC) &_optiRum_pv_cpp, 3},
    {"_optiRum_ratecpp", (DL_FUNC) &_optiRum_ratecpp, 3},
    {"_optiRum_times_two", (DL_FUNC) &_optiRum_times_two, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_optiRum(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
