# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Calculates compounded interest rate
#' 
#' @param nper Number of periods
#' @param pmt Instalment per period (should be negative)
#' @param pv Present value i.e. loan advance (should be positive)
#' @export
ratecpp <- function(nper, pmt, pv) {
    .Call('_optiRum_ratecpp', PACKAGE = 'optiRum', nper, pmt, pv)
}

#' Multiply numbers
#' 
#' @param x integer
#' @export
times_two <- function(x) {
    .Call('_optiRum_times_two', PACKAGE = 'optiRum', x)
}

