# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param rate The nominal interest rate per period (should be positive)
#' @param nper Number of periods
#' @param pv Present value i.e. loan advance (should be positive)
#' @export 
pmt_cpp <- function(rate, nper, pv) {
    .Call('_optiRum_pmt_cpp', PACKAGE = 'optiRum', rate, nper, pv)
}

#'
#' @param rate The nominal interest rate per period (should be positive)
#' @param nper Number of periods
#' @param pmt Instalment per period (should be negative)
#' @param fv      Future value i.e. redemption amount
#' @export
pv_cpp <- function(rate, nper, pmt) {
    .Call('_optiRum_pv_cpp', PACKAGE = 'optiRum', rate, nper, pmt)
}

#'  Calculates compounded interest rate
#' 
#' @param nper Number of periods
#' @param pmt Instalment per period (should be negative)
#' @param pv Present value i.e. loan advance (should be positive)
#' @export
ratecpp <- function(nper, pmt, pv) {
    .Call('_optiRum_ratecpp', PACKAGE = 'optiRum', nper, pmt, pv)
}

#' Multiply numbers
#' 
#' @param x integer
#' @export
times_two <- function(x) {
    .Call('_optiRum_times_two', PACKAGE = 'optiRum', x)
}

